// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAPI.Data;

#nullable disable

namespace ProjectAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230429235529_ProjectApiMigration")]
    partial class ProjectApiMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectAPI.Model.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<bool>("Dostepny")
                        .HasColumnType("bit");

                    b.Property<int>("Ilosc")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Utworzony")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Zaktualizowany")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Produkts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cena = 10.0,
                            Dostepny = true,
                            Ilosc = 10,
                            Nazwa = "Kubek"
                        },
                        new
                        {
                            Id = 2,
                            Cena = 20.0,
                            Dostepny = false,
                            Ilosc = 0,
                            Nazwa = "Dlugopis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
